// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelGeneratorSourceDB.Data;

#nullable disable

namespace ModelGeneratorSourceDB.Data.Migrations
{
    [DbContext(typeof(HL7ModelContext))]
    [Migration("20260819101128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7Component", b =>
                {
                    b.Property<int?>("ComponentNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comp_no");

                    b.Property<string>("DataStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_structure");

                    b.Property<string>("DataTypeCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_Type_code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7Components", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7DataElement", b =>
                {
                    b.Property<int?>("DataItem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_item");

                    b.Property<string>("DataStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_structure");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("LengthOld")
                        .HasColumnType("TEXT")
                        .HasColumnName("length_old");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7DataElements", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7DataStructure", b =>
                {
                    b.Property<string>("DataStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_structure");

                    b.Property<string>("DataTypeCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type_code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7DataStructures", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7DataStructureComponent", b =>
                {
                    b.Property<int?>("ComponentNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comp_no");

                    b.Property<string>("DataStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_structure");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq_no");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_id");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7DataStructureComponents", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7DataType", b =>
                {
                    b.Property<string>("DataTypeCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_Type_code");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7DataTypes", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7EventMessageTypeSegment", b =>
                {
                    b.Property<string>("EventCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_code");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("groupname");

                    b.Property<string>("MessageType")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_type");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER")
                        .HasColumnName("optional");

                    b.Property<bool>("Repetitional")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repetitional");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7EventMessageTypeSegments", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7MsgStructId", b =>
                {
                    b.Property<string>("MessageStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_structure");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7MsgStructIDs", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7MsgStructIdSegment", b =>
                {
                    b.Property<string>("MessageStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_structure");

                    b.Property<string>("SegmentCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("seg_code");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7MsgStructIDSegments", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7Segment", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("SegmentCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("seg_code");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7Segments", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7SegmentDataElement", b =>
                {
                    b.Property<string>("Reqired")
                        .HasColumnType("TEXT")
                        .HasColumnName("req_opt");

                    b.Property<string>("SegmentCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("seg_code");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq_no");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7SegmentDataElements", (string)null);
                });

            modelBuilder.Entity("ModelGeneratorSourceDB.Model.HL7Version", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Hl7Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("hl7_version");

                    b.Property<int?>("VersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.ToTable("HL7Versions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
